// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0WRB7oaz4dPd0WW5JPiT4lz30GPgSFdo',
    appId: '1:506777513579:web:fb067559dab9e4fa4d0b2e',
    messagingSenderId: '506777513579',
    projectId: 'logintest-fe4cd',
    authDomain: 'logintest-fe4cd.firebaseapp.com',
    storageBucket: 'logintest-fe4cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDClV-fT_BoMSzFzsyzUuA70YKfVICijV0',
    appId: '1:506777513579:android:8c5f265ef64b9ffd4d0b2e',
    messagingSenderId: '506777513579',
    projectId: 'logintest-fe4cd',
    storageBucket: 'logintest-fe4cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3fYwp2O_22R9H9CEzaSwiy8A_tq9zaQ',
    appId: '1:506777513579:ios:7be572d12f2a37504d0b2e',
    messagingSenderId: '506777513579',
    projectId: 'logintest-fe4cd',
    storageBucket: 'logintest-fe4cd.appspot.com',
    iosBundleId: 'com.example.loginQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq3fYwp2O_22R9H9CEzaSwiy8A_tq9zaQ',
    appId: '1:506777513579:ios:7be572d12f2a37504d0b2e',
    messagingSenderId: '506777513579',
    projectId: 'logintest-fe4cd',
    storageBucket: 'logintest-fe4cd.appspot.com',
    iosBundleId: 'com.example.loginQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0WRB7oaz4dPd0WW5JPiT4lz30GPgSFdo',
    appId: '1:506777513579:web:80c57e7cf58322ef4d0b2e',
    messagingSenderId: '506777513579',
    projectId: 'logintest-fe4cd',
    authDomain: 'logintest-fe4cd.firebaseapp.com',
    storageBucket: 'logintest-fe4cd.appspot.com',
  );
}
